# Generated by Django 6.0 on 2026-01-02 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_age_rating_movie_is_coming_soon_movie_is_hero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies', to='movies.genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='is_coming_soon',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='is_hero',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='is_trending',
            field=models.BooleanField(),
        ),
    ]
