# Generated by Django 6.0 on 2026-01-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_genre_alter_movie_is_coming_soon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='is_coming_soon',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='movie',
            name='is_hero',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='movie',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
    ]
