# Generated by Django 6.0 on 2026-01-02 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_movie_is_coming_soon_alter_movie_is_hero_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='trailer_url',
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=models.FileField(blank=True, null=True, upload_to='movie_trailers/'),
        ),
    ]
