# Generated by Django 6.0 on 2026-01-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_remove_movie_trailer_url_movie_trailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='horizontal_poster',
            field=models.ImageField(blank=True, help_text='Large horizontal poster for hero/banner sections', null=True, upload_to='movie_posters/'),
        ),
    ]
